---
language: node_js

node_js:
  - "4.1.0"

sudo: false

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

install:
  - npm install -g broccoli-cli
  - npm install -g mocha
  - npm install

script:
  - make install
